name: Build and Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  SOLUTION_LOCATION: Disperse
  SOLUTION_FILE_NAME: Disperse.sln
  EXECUTABLE_NAME: Disperse.exe
  UNIT_TEST_EXECUTABLE_NAME: UnitTesting.exe  
  INTEGRATION_TEST_LOCATION: Testing/Integration
  INTEGRATION_TEST_COMMAND: ./Test.bat
  UNIT_TEST_LOCATION: Testing/UnitTesting

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Set up NuGet
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: '5.x'

    - name: Restore NuGet packages
      working-directory: ${{env.SOLUTION_LOCATION}}    
      run: nuget restore ${{env.SOLUTION_FILE_NAME}}

    - name: Build
      working-directory: ${{env.SOLUTION_LOCATION}}
      run: msbuild /m /p:Platform=x64 /p:Configuration=Release ${{env.SOLUTION_FILE_NAME}}

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.EXECUTABLE_NAME}}
        path: ${{env.SOLUTION_LOCATION}}/x64/Release/${{env.EXECUTABLE_NAME}}

    - name: Upload unit test binary
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.UNIT_TEST_EXECUTABLE_NAME}}
        path: ${{env.SOLUTION_LOCATION}}/x64/Release/${{env.UNIT_TEST_EXECUTABLE_NAME}}

  integration_test:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Retrieve built binary
      uses: actions/download-artifact@v4
      with:
        name: ${{env.EXECUTABLE_NAME}}
        path: ${{env.INTEGRATION_TEST_LOCATION}}
        
    - name: Run tests
      working-directory: ${{env.INTEGRATION_TEST_LOCATION}}
      run: ${{env.TEST_COMMAND}}

  unit_test:
    runs-on: windows-latest
    needs: build
  
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Retrieve built binary
      uses: actions/download-artifact@v4
      with:
        name: ${{env.UNIT_TEST_EXECUTABLE_NAME}}
        path: ${{env.UNIT_TEST_LOCATION}}

    - name: Run tests
      working-directory: ${{env.UNIT_TEST_LOCATION}}
      run: ./${{env.UNIT_TEST_EXECUTABLE_NAME}}
