name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_LOCATION: Disperse
  SOLUTION_FILE_NAME: Disperse.sln

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}\${{env.SOLUTION_LOCATION}}
      run: msbuild /m /p:Platform=x64 /p:Configuration=Release ${{env.SOLUTION_FILE_NAME}}
