name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_LOCATION: Disperse
  SOLUTION_FILE_NAME: Disperse.sln
  EXECUTABLE_NAME: Disperse.exe
  TEST_LOCATION: Testing/Integration
  TEST_COMMAND: Test.bat

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{env.SOLUTION_LOCATION}}
      run: msbuild /m /p:Platform=x64 /p:Configuration=Release ${{env.SOLUTION_FILE_NAME}}

    - name: Upload built binary
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.EXECUTABLE_NAME}}
        path: ${{env.SOLUTION_LOCATION}}/x64/Release/${{env.EXECUTABLE_NAME}}

  test:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Retrieve built binary
      uses: actions/download-artifact@v4
      with:
        name: ${{env.EXECUTABLE_NAME}}
        path: ${{env.TEST_LOCATION}}
        
    - name: Run tests
      working-directory: ${{env.TEST_LOCATION}}
      run: ${{env.TEST_LOCATION}}/${{env.TEST_COMMAND}}
